import pandas as pd
from ta.momentum import RSIIndicator
from ta.trend import MACD
from ta.volatility import BollingerBands

# Read CSV generated by yfinance
df = pd.read_csv("data/stock_data.csv", skiprows=2)

# Rename columns
df.columns = ["Date", "Close", "High", "Low", "Open", "Volume"]

# Convert columns to numeric
df["Close"] = pd.to_numeric(df["Close"], errors="coerce")
df["High"] = pd.to_numeric(df["High"], errors="coerce")
df["Low"] = pd.to_numeric(df["Low"], errors="coerce")
df["Open"] = pd.to_numeric(df["Open"], errors="coerce")
df["Volume"] = pd.to_numeric(df["Volume"], errors="coerce")

# Remove missing values
df = df.dropna()

# RSI
df["RSI"] = RSIIndicator(close=df["Close"]).rsi()

# MACD
macd = MACD(close=df["Close"])
df["MACD"] = macd.macd()

# Bollinger Bands
bb = BollingerBands(close=df["Close"])

df["BB_Upper"] = bb.bollinger_hband()
df["BB_Lower"] = bb.bollinger_lband()

# Save updated file
df.to_csv("data/stock_data_with_indicators.csv", index=False)

print(df[["Close", "RSI", "MACD", "BB_Upper", "BB_Lower"]].tail())

print("\nIndicators calculated successfully!")